version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-DEV
    working_dir: /app/src/
    volumes:
      - .:/app
    ports:
      - 8000:8000
    entrypoint: ["sh", "../docker-entrypoint.sh"]
    

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
